obj-$(CONFIG_MACH_FLYER) += board-flyer.o
obj-$(CONFIG_MACH_FLYER) += board-flyer-audio.o
obj-$(CONFIG_MACH_FLYER) += board-flyer-keypad.o
obj-$(CONFIG_MACH_FLYER) += board-flyer-microp.o
obj-$(CONFIG_MACH_FLYER) += board-flyer-mmc.o
ifeq ($(CONFIG_FB_MSM_NEW),y)
obj-$(CONFIG_MACH_FLYER) += board-flyer-panel.o
else
obj-$(CONFIG_MACH_FLYER) += board-flyer-panel-legacy.o
endif
obj-$(CONFIG_MACH_FLYER) += board-flyer-rfkill.o
obj-$(CONFIG_MACH_FLYER) += board-flyer-wifi.o
obj-$(CONFIG_MACH_FLYER) += board-flyer-regulator.o
